version: '3.8'

services:
  backend:
    image: subu3284/global-temp-backend:latest
    container_name: global_temp_backend
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"   # Locked to localhost
    env_file:
      - .env

  frontend:
    image: subu3284/global-temp-frontend:latest
    container_name: global_temp_frontend
    restart: unless-stopped
    ports:
      - "4000:80"    # Locked to localhost on port 4000
    depends_on:
      - backend
