version: '3.8'

services:
  backend:
    image: subu3284/global-temp-backend:latest
    container_name: global_temp_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    image: subu3284/global-temp-frontend:latest
    container_name: global_temp_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend